"""initial schema: core MVP tables

Revision ID: 9cd8bdb26161
Revises: 
Create Date: 2026-07-11 08:27:17.412708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cd8bdb26161'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('letter', sa.String(length=4), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('text_ar', sa.Text(), nullable=False),
    sa.Column('image_ref', sa.String(length=512), nullable=True),
    sa.Column('audio_ref', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('word', 'phrase', 'sentence', 'story')", name='ck_level_valid'),
    sa.CheckConstraint("position IN ('initial', 'medial', 'final')", name='ck_position_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_letter'), 'activities', ['letter'], unique=False)
    op.create_table('users',
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('parent', 'slp', 'admin')", name='ck_role_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('children',
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=8), nullable=False),
    sa.Column('dialect', sa.String(length=16), nullable=False),
    sa.Column('consent_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sex IN ('male', 'female')", name='ck_sex_valid'),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_guardian_id'), 'children', ['guardian_id'], unique=False)
    op.create_table('assessments',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=True),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('screening', 'articulation')", name='ck_type_valid'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_child_id'), 'assessments', ['child_id'], unique=False)
    op.create_table('phoneme_profiles',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('phoneme', sa.String(length=4), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('gop_score', sa.SmallInteger(), nullable=False),
    sa.Column('error_type', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position IN ('initial', 'medial', 'final')", name='ck_position_valid'),
    sa.CheckConstraint('gop_score >= 0 AND gop_score <= 100', name='ck_gop_score_range'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_phoneme_profiles_child_phoneme_position', 'phoneme_profiles', ['child_id', 'phoneme', 'position'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=8), nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_phonemes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("author IN ('ai', 'slp')", name='ck_author_valid'),
    sa.CheckConstraint("status IN ('draft', 'approved', 'active')", name='ck_status_valid'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_child_id'), 'treatment_plans', ['child_id'], unique=False)
    op.create_table('sessions',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('activity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adherence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('adherence IS NULL OR (adherence >= 0 AND adherence <= 1)', name='ck_adherence_range'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_child_id'), 'sessions', ['child_id'], unique=False)
    op.create_index(op.f('ix_sessions_plan_id'), 'sessions', ['plan_id'], unique=False)
    op.create_table('recordings',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('audio_uri', sa.String(length=512), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_session_id'), 'recordings', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_session_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_sessions_plan_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_child_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_treatment_plans_child_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index('ix_phoneme_profiles_child_phoneme_position', table_name='phoneme_profiles')
    op.drop_table('phoneme_profiles')
    op.drop_index(op.f('ix_assessments_child_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_children_guardian_id'), table_name='children')
    op.drop_table('children')
    op.drop_table('users')
    op.drop_index(op.f('ix_activities_letter'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
