#!/usr/bin/env python3
"""Generate docs/data-dictionary.md from the code that enforces it.

The dataset contracts and the metric catalogue are the single source of
truth. Writing the dictionary by hand guarantees it drifts from the
validator within a release, so it is generated instead.

Usage:
    python scripts/build_data_dictionary.py
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from app.analytics.benchmarks import CATALOGUE          # noqa: E402
from app.ingest.datasets import DATASETS, LOAD_ORDER    # noqa: E402

TYPE_NAMES = {
    "string": "text",
    "integer": "integer",
    "number": "decimal",
    "boolean": "Y/N",
    "datetime": "timestamp",
    "date": "date",
}

DOMAIN_ORDER = ["capacity", "ed", "journey", "quality", "nursing"]
DOMAIN_TITLES = {
    "capacity": "Capacity and bed management",
    "ed": "Emergency department",
    "journey": "Patient journey and turnaround",
    "quality": "Quality and patient safety",
    "nursing": "Nursing and workforce",
}


def escape(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ")


def dataset_section(key: str) -> list[str]:
    spec = DATASETS[key]
    lines = [
        f"### `{spec.key}` — {spec.title_en}",
        "",
        f"*{spec.title_ar}*",
        "",
        f"- **Identified by:** {' + '.join(f'`{k}`' for k in spec.natural_key)}",
        f"- **Required fields:** "
        f"{', '.join(f'`{f}`' for f in spec.required_fields) or 'none'}",
    ]
    if spec.references_encounter:
        lines.append(
            "- **Depends on:** `encounters` must be loaded first — rows referring "
            "to an unknown encounter number are quarantined."
        )
    if spec.notes:
        lines.append(f"- **Note:** {spec.notes}")

    if spec.chronology:
        pairs = ", ".join(f"`{r.earlier}` ≤ `{r.later}`" for r in spec.chronology)
        lines.append(f"- **Ordering enforced:** {pairs}")

    lines += [
        "",
        "| Field | Type | Required | Accepted values | Range | Also recognised as | Notes |",
        "|---|---|---|---|---|---|---|",
    ]

    for field in spec.fields:
        bounds = ""
        if field.minimum is not None or field.maximum is not None:
            low = field.minimum if field.minimum is not None else "−∞"
            high = field.maximum if field.maximum is not None else "∞"
            bounds = f"{low} – {high}"
        domain = ", ".join(f"`{d}`" for d in field.domain) if field.domain else ""
        aliases = ", ".join(field.aliases[:5])
        note = field.description
        # Only add the identifier warning if the description has not
        # already made the point, so it appears once rather than twice.
        if field.is_identifier and "hashed" not in note.lower():
            note = (note + " **Hashed on ingest; never stored raw.**").strip()
        lines.append(
            f"| `{field.name}` | {TYPE_NAMES.get(field.dtype, field.dtype)} "
            f"| {'**yes**' if field.required else 'no'} | {escape(domain)} "
            f"| {bounds} | {escape(aliases)} | {escape(note)} |"
        )
    lines.append("")
    return lines


def metric_section(domain: str) -> list[str]:
    metrics = [m for m in CATALOGUE.values() if m.domain == domain]
    if not metrics:
        return []

    lines = [
        f"### {DOMAIN_TITLES.get(domain, domain.title())}",
        "",
        "| Metric | Arabic | Unit | Definition | Numerator | Denominator | Target | Amber | Red | Direction | Source |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for m in sorted(metrics, key=lambda x: x.key):
        direction = "higher is better" if m.higher_is_better else "lower is better"
        lines.append(
            f"| `{m.key}` — {escape(m.label_en)} | {escape(m.label_ar)} | {m.unit} "
            f"| {escape(m.definition_en)} | {escape(m.numerator_en)} "
            f"| {escape(m.denominator_en)} "
            f"| {'' if m.target is None else m.target} "
            f"| {'' if m.amber is None else m.amber} "
            f"| {'' if m.red is None else m.red} | {direction} | {m.source} |"
        )
    lines.append("")
    return lines


def build() -> str:
    lines = [
        "# Data dictionary",
        "",
        "> Generated by `scripts/build_data_dictionary.py` from the dataset",
        "> contracts in `backend/app/ingest/datasets.py` and the metric",
        "> catalogue in `backend/app/analytics/benchmarks.py`. Edit those,",
        "> not this file.",
        "",
        f"Generated {date.today().isoformat()} · "
        f"{len(DATASETS)} datasets · {len(CATALOGUE)} metrics",
        "",
        "---",
        "",
        "## Part 1 — Import datasets",
        "",
        "Every column a hospital can supply, what the platform calls it, and "
        "the header spellings it recognises automatically. Column names do "
        "**not** have to match: the loader resolves whatever the file "
        "contains and reports anything it could not place.",
        "",
        "**Load order** (later datasets reference earlier ones): "
        + " → ".join(f"`{k}`" for k in LOAD_ORDER),
        "",
    ]
    for key in LOAD_ORDER:
        lines += dataset_section(key)

    lines += [
        "---",
        "",
        "## Part 2 — Metric catalogue",
        "",
        "Every indicator the platform computes, with its definition and its "
        "default red/amber/green thresholds. Thresholds are starting points "
        "for a tertiary centre and are overridden per facility through "
        "`PUT /api/v1/admin/benchmarks`, which is why the API always returns "
        "the target alongside the value.",
        "",
        "Sources: **CBAHI** Saudi Central Board for Accreditation of "
        "Healthcare Institutions · **JCI** Joint Commission International · "
        "**MAGNET** ANCC Magnet Recognition / NDNQI · **HSTP** Saudi Health "
        "Sector Transformation Programme · **INTERNAL** operational "
        "convention with no external standard.",
        "",
    ]
    for domain in DOMAIN_ORDER:
        lines += metric_section(domain)

    lines += [
        "---",
        "",
        "## Part 3 — Conventions that affect every number",
        "",
        "**Patient days are occupancy-weighted, not midnight census.** A stay "
        "from 22:00 Monday to 06:00 Wednesday contributes 0.083 days to "
        "Monday, 1.0 to Tuesday and 0.25 to Wednesday. Midnight counting "
        "makes short-stay and observation activity disappear.",
        "",
        "**Timing indicators report medians.** ED and journey intervals have "
        "long right tails; one 30-hour boarder moves a mean far more than it "
        "moves the typical patient's experience. The 90th percentile is "
        "carried in each tile's `context` so the tail stays visible.",
        "",
        "**Harm rates count hospital-acquired events only.** Events flagged "
        "`present_on_admission` are excluded from the numerator. Mixing the "
        "two is the most common reason an infection rate fails an "
        "accreditation survey.",
        "",
        "**Emergency treatment spaces are not inpatient beds.** They are "
        "excluded from the occupancy denominator and reported separately by "
        "the emergency module. Nursing indicators do include the ED, because "
        "emergency nurses care for real patients whose hours need a real "
        "denominator.",
        "",
        "**Rates return `null`, never zero, when the denominator is empty.** "
        "A closed unit reports \"no data\", not 0%.",
        "",
        "**Readmission looks forward past the reporting window.** The "
        "denominator is index discharges inside the period; the numerator "
        "searches the following 30 days, so the repository deliberately "
        "loads a wider slice than the window itself.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    output = ROOT / "docs" / "data-dictionary.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build(), encoding="utf-8")

    fields = sum(len(s.fields) for s in DATASETS.values())
    print(f"Wrote {output.relative_to(ROOT)}")
    print(f"  {len(DATASETS)} datasets, {fields} fields, {len(CATALOGUE)} metrics")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
